spring:
  profiles:
     active:
     - dev
---
server: 
   port: 8201 

spring:
  profiles: dev      #如果说选举的策略是dev 表示：当前是开发环境
  application: 
     name: microservicecloud-config-client

eureka: 
  client: 
    service-url: 
       defaultZone: http://eureka-dev.com:7001/eureka/

---
server: 
  port: 8202
 
spring:
  profiles: test     #如果说选举的策略是 test表示：当前是测试环境
  application: 
    name: microservicecloud-config-client

eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-test.com:7001/eureka/
