#文件头信息
spring: 
 profiles: 
  active: 
    - dev

    
    
---
#注册中心占用7001端口,冒号后面必须要有空格
server: 
  port: 7001


spring: 
  #指定（选举策略配置项）如果说选举的策略是dev 表示：当前是开发环境
  profiles: dev
  
  #（当前服务上下文名称）
  application:
   name: microservicecloud-config-eureka-client


   
   
eureka: 
  instance: 
    #指定 （当前 Eureka服务端的  服务地址）
    hostname: eureka7001.com #冒号后面必须要有空格
  
  #客户端的配置
  client: 
    #当前的eureka-server自己不注册进服务列表中
    register-with-eureka: false
    #不通过eureka获取注册信息
    fetch-registry: false
    #设置与【Eureka Server注册中心交互时，向外暴露的地址】
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/


      
      
---
server: 
  #注册中心占用7001端口,冒号后面必须要有空格
  port: 7001
  
  
spring: 
  #指定（选举策略配置项）如果说选举的策略是 test表示：当前是测试环境
  profiles: test
  
  #（当前服务上下文名称）
  application:
   name: microservicecloud-config-eureka-client
   
   
   
eureka: 
  instance: 
    #指定 （当前 Eureka服务端的  服务地址）
    hostname: eureka7001.com
  
  #客户端的配置
  client: 
    #当前的eureka-server自己不注册进服务列表中
    register-with-eureka: false
    
    #不通过eureka获取注册信息
    fetch-registry: false
    #设置与【Eureka Server注册中心交互时，向外暴露的地址】
    service-url: 
     defaultZone: http://eureka7001.com:7001/eureka/